// Builds index.html: one self-contained file with the app, its styles and React inlined.
// Run: npm install, then npm run build.

import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";

const require = createRequire(import.meta.url);
const work = mkdtempSync(join(tmpdir(), "fabry-build-"));

// 1. JavaScript: the app plus React, minified into one script.
const js = await build({
  entryPoints: ["src/main.jsx"],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2020", "safari15", "chrome90", "firefox90"],
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  legalComments: "none",
  write: false,
});
const script = js.outputFiles[0].text
  .replace(/<\/script/gi, "<\\/script")
  .replace(/<!--/g, "<\\!--");

// 2. CSS: only the Tailwind classes the app uses.
const cssIn = join(work, "in.css");
const cssOut = join(work, "out.css");
writeFileSync(cssIn, "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n");
execFileSync(process.execPath, [
  require.resolve("tailwindcss/lib/cli.js"),
  "-c", "tailwind.config.cjs", "-i", cssIn, "-o", cssOut, "--minify",
], { stdio: "inherit" });
const css = readFileSync(cssOut, "utf8");
rmSync(work, { recursive: true, force: true });

// 3. A content security policy that only lets the page talk to the services it uses.
const scriptHash = createHash("sha256").update(script).digest("base64");
const csp = [
  "default-src 'none'",
  `script-src 'sha256-${scriptHash}'`,
  "style-src 'unsafe-inline' https://fonts.googleapis.com",
  "font-src https://fonts.gstatic.com",
  "img-src data: 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "connect-src https://eutils.ncbi.nlm.nih.gov https://clinicaltrials.gov",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

const icon = "data:image/svg+xml," + encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#0B4F57"/>' +
  '<polyline points="12,44 24,34 34,38 52,18" fill="none" stroke="#fff" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg>'
);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta http-equiv="Content-Security-Policy" content="${csp}">
<meta name="referrer" content="no-referrer">
<title>Fabry Tracker</title>
<meta name="description" content="Fabry Tracker helps people living with Fabry disease keep their lab results, treatments and symptoms in one place.">
<meta name="theme-color" content="#0B4F57">
<meta name="color-scheme" content="light dark">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Fabry Tracker">
<link rel="icon" href="${icon}">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap">
<style>${css}
html,body{background:var(--bg,#EEF2F4);margin:0}
body{font-family:'Atkinson Hyperlegible',system-ui,-apple-system,'Segoe UI',sans-serif;color:var(--ink,#1B2B3A)}
</style>
</head>
<body>
<div id="root"></div>
<noscript><p style="padding:24px">Fabry Tracker needs JavaScript. Please turn it on in your browser settings.</p></noscript>
<script>${script}</script>
</body>
</html>
`;

writeFileSync("index.html", html);

// 4. Service worker for offline use. Its cache name changes with every build, so phones pick up updates.
const version = createHash("sha256").update(html).digest("hex").slice(0, 12);
writeFileSync("sw.js", `// Fabry Tracker offline support. Generated by build.mjs.
const CACHE = "fabry-tracker-${version}";
const FILES = ["./", "./index.html", "./manifest.webmanifest", "./icons/icon-192.png", "./icons/icon-512.png",
  "./icons/icon-maskable-512.png", "./icons/apple-touch-icon.png"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith("fabry-tracker-") && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Only the app's own files are cached. Trial and article searches always go to the network.
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    // Newest page when online, saved copy when offline.
    event.respondWith(fetch(req)
      .then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put("./index.html", copy)); return res; })
      .catch(() => caches.match("./index.html")));
    return;
  }
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
`);
console.log(`index.html written: ${(Buffer.byteLength(html) / 1024).toFixed(0)} KB, sw.js cache ${version}`);
