// Rare Disease Tracker offline support. Generated by build.mjs.
const CACHE = "rdt-beta-d8d4a64fa3fa";
// This worker looks after only the app page in its own folder. Other pages (terms.html, a beta/ folder) are left alone.
const ROOT = new URL("./", self.location).pathname;
const isAppPage = (url) => { const p = new URL(url).pathname; return p === ROOT || p === ROOT + "index.html"; };
const FILES = ["./", "./index.html", "./manifest.webmanifest", "./icon-192.png", "./icon-512.png",
  "./icon-maskable-512.png", "./apple-touch-icon.png"];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith("rdt-beta-") && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Only the app's own files are cached. Trial and article searches always go to the network.
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    if (!isAppPage(req.url)) return;
    // Newest page when online, saved copy when offline.
    event.respondWith(fetch(req)
      .then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put("./index.html", copy)); return res; })
      .catch(() => caches.match("./index.html")));
    return;
  }
  // Translations: newest when online, saved copy when offline.
  const path = new URL(req.url).pathname;
  if (path.startsWith(ROOT + "lang/") || (path.startsWith(ROOT) && path.endsWith(".json") && !path.slice(ROOT.length).includes("/"))) {
    event.respondWith(fetch(req)
      .then((res) => { if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); } return res; })
      .catch(() => caches.match(req)));
    return;
  }
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
